SHELL := bash

#PATTERN := HRGTA
PATTERN := $(shell cat PATTERN)
ifndef PATTERN
$(error PATTERN is undefined)
endif

motif_ipds := motif_ipd.ab.csv motif_ipd.cd.csv
motif_wga_ipdratios := motif_ipdratio.ab.csv motif_ipdratio.cd.csv
motif_hawaiian_ipdratios := motif_ipdratio.PD2182.csv motif_ipdratio.PD2182sequel.csv
motif_ipdratios := motif_ipdratio.k_normBy_ab.csv motif_ipdratio.l_normBy_cd.csv
motif_kinetics_csv := $(motif_ipds) motif_ipd.PD2182.csv motif_ipd.PD2182sequel.csv $(motif_ipdratios)
motif_kinetics_csv_celegans := $(motif_kinetics_csv:.csv=.c_elegans.csv)
motif_kinetics_pdf := plot_motif_kinetics.pdf
motif_kinetics_stderr_pdf := plot_motif_kinetics.stderr.pdf
motif_kinetics_stderr_widey_pdf := plot_motif_kinetics.stderr.wide_y.pdf
cor_pdf := plot_kinetics_correlation.pdf
cor_pdf2 := plot_ipdratio_correlation.pdf
cor_pdf_celegans := plot_kinetics_correlation.c_elegans.pdf
cor_pdf2_celegans := plot_ipdratio_correlation.c_elegans.pdf

.SECONDEXPANSION:
target := $(motif_kinetics_pdf) $(motif_kinetics_stderr_pdf) $(motif_kinetics_stderr_widey_pdf) $(cor_pdf) $(motif_wga_ipdratios) $(motif_hawaiian_ipdratios) $(cor_pdf2)
target += $(motif_kinetics_csv_celegans) #$(cor_pdf_celegans) $(cor_pdf2_celegans)
all: $$(target)

.DELETE_ON_ERROR:

# NOTE: It is important to use non-merged files after slopping/extension (*.slop20.bed.fa),
# rather than merged files (*.slop20.merged.bed.fa) for locating motifs near feature loci.
# I want to exclude occurrences of motifs at the edges of extended regions:
# --xxxxxXxxxxx------------
# ------------xxxxxXxxxxx--
# ---YYY-----YYY-----------
# X: feature locus
# x: extended region
# YYY: target motif
# The first motif should be captured, but the second should be ignored.

# pattern occurrence for background
occ_background := $(PATTERN).ab.bed $(PATTERN).cd.bed $(PATTERN).ce11rel606.bed $(PATTERN).k_normBy_ab.bed $(PATTERN).l_normBy_cd.bed $(PATTERN).PD2182.bed $(PATTERN).PD2182sequel.bed
$(PATTERN).ce11rel606.bed: /glusterfs/hisakatha/ce11rel606/ce11rel606.fa
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
DIR := /glusterfs/hisakatha/methylation/smrtpipe/vs_ce11rel606
FILE := mapped.alignmentset.merged.bam.cov25.slop20.bed.fa
$(PATTERN).ab.bed: $(DIR)/jun2018_ab_pcr_vc2010_op50/$(FILE)
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
$(PATTERN).cd.bed: $(DIR)/jun2018_cd_pcr_vc2010/$(FILE)
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
$(PATTERN).PD2182.bed: $(DIR)/PD2182-20150119/$(FILE)
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
$(PATTERN).PD2182sequel.bed: $(DIR)/PD2182-sequel/$(FILE)
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
$(PATTERN).k_normBy_ab.bed: $(DIR)/jun2018_analysis/deep_region_cov25.k_normBy_ab.slop20.bed.fa
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@
$(PATTERN).l_normBy_cd.bed: $(DIR)/jun2018_analysis/deep_region_cov25.l_normBy_cd.slop20.bed.fa
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@

deep_kinetics_beds := $(wildcard ../../deep_kinetics_region.*.slop20.bed.fa)
occ_deep_kinetics := $(deep_kinetics_beds:../../%=$(PATTERN).%.bed)
$(occ_deep_kinetics): $(PATTERN).%.bed: ../../%
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@

# pattern occurrence for features (such as DNA modification and high IPD)
occ_feature_fa := $(wildcard ../../*.slop20.fullLength.gff.fa)
occ_feature := $(occ_feature_fa:../../%=$(PATTERN).%.bed)
$(occ_feature): $(PATTERN).%.bed: ../../%
	seqkit locate --bed -i -d -p $(PATTERN) $< > $@ && touch $@

occ := $(occ_background) $(occ_feature) $(occ_deep_kinetics)
merged_occ := $(occ:=.merged_occ)
$(merged_occ): %.merged_occ: %
	cat $< | ../merge_occurrence.sh > $@ && touch $@

target += $(merged_occ)

# These lines require a lot of RAM
$(motif_ipds): get_motif_ipd.R.log
	touch $@
get_motif_ipd.R.log: $(PATTERN).deep_kinetics_region.ab.bed.merged.sorted.slop20.bed.fa.bed.merged_occ $(PATTERN).deep_kinetics_region.cd.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipd.v2.R $(PATTERN) &> $@ && touch $@
$(motif_wga_ipdratios): get_motif_wga_ipdratio.R.log
	touch $@
get_motif_wga_ipdratio.R.log: $(PATTERN).deep_kinetics_region.ab.bed.merged.sorted.slop20.bed.fa.bed.merged_occ $(PATTERN).deep_kinetics_region.cd.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_wga_ipdratio.R $(PATTERN) &> $@ && touch $@
motif_ipd.PD2182.csv: $(PATTERN).deep_kinetics_region.PD2182.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipd.PD2182.v2.R $(PATTERN) &> get_motif_ipd.PD2182.R.log && touch $@
motif_ipd.PD2182sequel.csv: $(PATTERN).deep_kinetics_region.PD2182sequel.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipd.PD2182sequel.v2.R $(PATTERN) &> get_motif_ipd.PD2182sequel.R.log && touch $@
$(motif_ipdratios): get_motif_ipdratio.R.log
	touch $@
get_motif_ipdratio.R.log: $(PATTERN).deep_kinetics_region.k_normBy_ab.bed.slop20.bed.fa.bed.merged_occ $(PATTERN).deep_kinetics_region.l_normBy_cd.bed.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipdratio.v2.R $(PATTERN) &> $@ && touch $@

motif_ipdratio.PD2182.csv: $(PATTERN).deep_kinetics_region.PD2182.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipdratio.PD2182.R $(PATTERN) &> get_motif_ipdratio.PD2182.R.log && touch $@
motif_ipdratio.PD2182sequel.csv: $(PATTERN).deep_kinetics_region.PD2182sequel.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipdratio.PD2182sequel.R $(PATTERN) &> get_motif_ipdratio.PD2182sequel.R.log && touch $@

motif_ipd.k.csv: $(PATTERN).deep_kinetics_region.k.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipd.k.v2.R $(PATTERN) &> get_motif_ipd.k.R.log && touch $@
motif_ipd.l.csv: $(PATTERN).deep_kinetics_region.l.bed.merged.sorted.slop20.bed.fa.bed.merged_occ
	Rscript ../get_motif_ipd.l.v2.R $(PATTERN) &> get_motif_ipd.l.R.log && touch $@

$(motif_kinetics_csv_celegans): %.c_elegans.csv: %.csv
	sample=$$(echo $< | sed -E "s/motif[_0-9a-zA-Z]+\.([_0-9a-zA-Z]+)\.csv/\1/"); \
	Rscript ../extract_celegans_data.R $< $(PATTERN).deep_kinetics_region.$${sample}.bed*.slop20.bed.fa.bed.merged_occ $@

$(motif_kinetics_pdf): $(motif_kinetics_csv)
	Rscript ../plot_motif_kinetics.R $(PATTERN) && touch $@

$(motif_kinetics_stderr_pdf): $(motif_kinetics_csv)
	Rscript ../plot_motif_kinetics.stderr.R $(PATTERN) && touch $@

$(motif_kinetics_stderr_widey_pdf): $(motif_kinetics_csv)
	Rscript ../plot_motif_kinetics.stderr.wide_y.R $(PATTERN) && touch $@

$(cor_pdf): $(motif_kinetics_csv)
	Rscript ../plot_kinetics_correlation.R

$(cor_pdf2): $(motif_wga_ipdratios) $(motif_hawaiian_ipdratios)
	Rscript ../plot_ipdratio_correlation.R
